Feature/yan 20
PapakhinAV/yandex-practicum-game pull request #11
Opened 2023-07-25 22:22 UTC by toropovofficial

### Добавил страницу регистрации, внес небольшие правки в глобальный компонент инпут для стилей

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-26 05:11 UTC, PapakhinAV requested changes

2023-07-26 05:11 UTC, PapakhinAV commented on packages/client/src/components/Form/types.ts
> +  className: string
давай его сделаем опциональным?
`className?: string`

2023-07-26 05:11 UTC, PapakhinAV commented on packages/client/src/components/fields/Input/Input.tsx
> +  return <Input bg="white" {...props} className={classNames(className)} />
а вот тут как раз можно использовать classNames - убрать bg="white" и перенести в стили его.
а цвет можно в константу положить
(https://github.com/PapakhinAV/yandex-practicum-game/pull/10/files#diff-18b10a3d27d57603ced4267c0414d456d08b9d07d1240347f00b95d819b381e1R8)

` return <Input {...props} className={classNames(className, styles.someClassName)} />`

2023-07-26 05:11 UTC, PapakhinAV commented on packages/client/src/pages/Register/Register.tsx
> +          <React.Fragment>
<React.Fragment></React.Fragment> можно записывать как <></>

2023-07-26 05:11 UTC, PapakhinAV commented on packages/client/src/pages/Register/Register.tsx
> +import CustomInput from '../../components/fields/Input/Input'
Для использования внутри формы есть FormInput, который специально подготовлен для формы. Твои правки обычного инпута не нужно туда переносить в FormInput, т.к. они там уже будут - он использует обычный инпут, но добавляет вокруг него несколько элементов.

packages/client/src/components/formFields/FormInput/FormInput.tsx

2023-07-26 05:11 UTC, PapakhinAV commented on packages/client/src/pages/Register/register.module.scss
> +        color: #0085FF;
выше давал ссылку на коммит в котором цвета выносились в переменную, давай тут (во всём файле) тоже так сделаем? Чтобы в дальнейшем не было 3 оттенков синего и 4 оттенков красного, а были 2 переменные "синий" и "красный" 😊

2023-07-27 16:49 UTC, toropovofficial commented
''

2023-07-27 16:50 UTC, toropovofficial commented
@PapakhinAV Глянь по правкам плз

2023-07-28 08:27 UTC, PapakhinAV commented on packages/client/src/components/fields/Input/Input.module.scss
> +  background: $base-text-color !important;
!important; 
Мне кажется, что это прям не очень практика, т.к. если потом где-то нужно переопределить - будет целая история)

2023-07-28 08:32 UTC, PapakhinAV submitted a review, later dismissed

2023-07-30 13:07 UTC, PapakhinAV submitted a review, later dismissed

2023-08-06 21:16 UTC, dmitriy-kochetkov commented on packages/client/src/components/fields/Input/Input.tsx
> +  return <Input bg={props.backgroundColor || 'white'} {...props} className={(className)} />
почему здесь убрал `register`?

2023-08-06 21:27 UTC, dmitriy-kochetkov submitted a review, later dismissed

2023-08-08 21:18 UTC, dmitriy-kochetkov approved these changes

2023-08-08 21:48 UTC, merged