Feature/yan 16
PapakhinAV/yandex-practicum-game pull request #12
Opened 2023-07-27 18:36 UTC by toropovofficial

### Сделал страницу логина, подключил роут

![login](https://github.com/PapakhinAV/yandex-practicum-game/assets/58236345/7c045fe4-8482-46a7-985c-1b33217a2b04)

2023-07-27 18:38 UTC, toropovofficial commented
@PapakhinAV @dmitriy-kochetkov

2023-07-29 07:35 UTC, apdashi approved these changes

2023-07-29 07:35 UTC, apdashi commented on packages/client/src/pages/Login/Login.tsx
> +          <svg
SVG лучше вынести из кода в статику

2023-07-29 07:35 UTC, apdashi commented on packages/client/src/components/formFields/FormInput/types.ts
> +  bg?: string
По имени переменной не понятно за что в ней должно быть.

2023-07-29 07:35 UTC, apdashi commented on packages/client/src/components/Form/Form.tsx
> +       <Form className={className} onSubmit={onSubmit}>
FYI желательно, если больше 1 параметра, то каждый параметр должен идти с новой строки

2023-07-29 10:47 UTC, dmitriy-kochetkov commented on packages/client/src/components/formFields/FormInput/types.ts
> +  bg?: string
> По имени переменной не понятно за что в ней должно быть.

тут `bg` совпадает с именем такой же переменной в chakra-ui.

Может лучше пробросить сюда тип `CustomInputProps` из components/fields/Input и объединить с этим типом, что-то вроде:

```
import { FieldValues } from 'react-hook-form'
import { CustomInputProps } from '../../fields'

export type FormInputProps = {
  name: keyof FieldValues,
} & CustomInputProps
```

2023-07-29 12:21 UTC, toropovofficial commented on packages/client/src/components/Form/Form.tsx
> +       <Form className={className} onSubmit={onSubmit}>
Думаю, что два - три параметра в строчку вполне допустимо. Если от двух параметров переносить, то сильно раздувается код

2023-07-29 21:18 UTC, IvanPeleshok commented on packages/client/src/pages/Login/Login.tsx
> +          {
Точно ли есть необходимость в фигурных скобках?

2023-07-29 21:19 UTC, IvanPeleshok commented on packages/client/src/pages/Login/Login.tsx
> +          <svg
Вынести в отдельный модуль и использовать, как обычный компонент

2023-07-29 21:23 UTC, IvanPeleshok commented on packages/client/src/pages/Login/Login.tsx
> +                <label>Пароль</label>
Ниже текст на английском (советую придерживаться одной локали)
Либо использовать react-i18next или её аналоги для поддержки нескольких локалей
https://react.i18next.com/

2023-07-29 21:24 UTC, IvanPeleshok commented on packages/client/src/components/formFields/FormInput/types.ts
> +  bg?: string
Поддерживаю

2023-07-29 21:24 UTC, IvanPeleshok approved these changes
Есть замечания

2023-07-31 09:31 UTC, apdashi commented on packages/client/src/components/Form/Form.tsx
> +       <Form className={className} onSubmit={onSubmit}>
Тут больше для ревью полезность, удобнее просмотр, из-за того что подствет строчки будет для конкретного параметра.

2023-07-31 09:34 UTC, apdashi commented on packages/client/src/components/formFields/FormInput/types.ts
> +  bg?: string
> Поддерживаю

КМК, в таком случае, желательно, полное имя использовать background, так как чакра поддерживает оба параметра

2023-07-31 10:41 UTC, apdashi commented on packages/client/src/components/formFields/FormInput/types.ts
> +  bg?: string
А вообще, если пропс содержит bg, то по коду оно перезапишет bg
и bg={props.bg || 'white'} - запись не имеет смысла

2023-08-04 21:12 UTC, IvanPeleshok requested changes
Есть замечания

2023-08-06 15:36 UTC, toropovofficial commented
@IvanPeleshok @PapakhinAV

2023-08-06 20:02 UTC, IvanPeleshok approved these changes
Всё супер, апрув

2023-08-06 20:32 UTC, dmitriy-kochetkov approved these changes

2023-08-07 06:46 UTC, dmitriy-kochetkov commented on packages/client/src/pages/Page404/Page404.tsx
этой страницы больше нет

2023-08-07 06:48 UTC, toropovofficial commented on packages/client/src/pages/Page404/Page404.tsx
Удалил

2023-08-07 06:50 UTC, dmitriy-kochetkov approved these changes

2023-08-07 06:50 UTC, merged