Feature/yan 17
PapakhinAV/yandex-practicum-game pull request #22
Opened 2023-08-12 13:27 UTC by toropovofficial

### 
Добавил логику авторизации
Добавил логику регистрации
Добавил валидацию для авторизации и регистрации
Переделал зависимость отображения страниц в роутинге с user на isAuth

![login](https://github.com/PapakhinAV/yandex-practicum-game/assets/58236345/202edc57-5f0c-4293-8615-dfb12eb0215b)

### TBD (если есть)
![register](https://github.com/PapakhinAV/yandex-practicum-game/assets/58236345/2171f6f9-01cb-4a6d-929c-46fa7886704d)

2023-08-12 16:10 UTC, toropovofficial commented
@dmitriy-kochetkov @apdashi @PapakhinAV

2023-08-12 16:36 UTC, dmitriy-kochetkov approved these changes

2023-08-13 19:37 UTC, IvanPeleshok commented on packages/client/src/core/Router/Routes.tsx
> +          !isAuth ? (
Предлагаю создать защищённый компонент, который будет отвечать за редирект в случае, если пользователь не авторизован, дабы избежать дублирования и добавить гибкости с масштабируемостью

Как пример, можно посмотреть на следующие статьи:

https://www.robinwieruch.de/react-router-private-routes/
https://ui.dev/react-router-protected-routes-authentication
https://medium.com/weekly-webtips/protect-your-route-with-protectedroute-and-guards-in-reactjs-2db83ec48860

2023-08-13 19:38 UTC, IvanPeleshok commented on packages/client/src/pages/Register/Register.tsx
> +  await signup(data).unwrap()
Необходимо форматирование

2023-08-13 19:38 UTC, IvanPeleshok requested changes
Есть предложение

2023-08-14 15:54 UTC, PapakhinAV submitted a review, later dismissed

2023-08-14 16:25 UTC, apdashi commented on packages/client/src/core/Router/Routes.tsx
> +  const isAuth = useSelector((state: IRootState) => state.app.isAuth)
По задаче "Авторизация должна проверяться через отдельно написанный Hook или HOC (на ваш выбор, можно использовать сразу оба)". Не совсем понятно, подходит ли такая реализация под хук

2023-08-14 16:27 UTC, toropovofficial commented on packages/client/src/core/Router/Routes.tsx
> +  const isAuth = useSelector((state: IRootState) => state.app.isAuth)
Обсудили уже это с @PapakhinAV, внесем правки на неделе доработок

2023-08-14 16:29 UTC, apdashi commented on packages/client/src/api/auth.ts
> +    signin: builder.mutation({
После авторизации нужно запросить данные user, и КМК после получения user можно считать что пользователь авторизован

2023-08-14 16:29 UTC, apdashi commented on packages/client/src/pages/Game/Game.tsx
> +        username: user?.login,
Если пользователь авторизован, то и данные о пользователе должны быть

2023-08-14 16:29 UTC, apdashi commented on packages/client/src/pages/Register/Register.tsx
> +  await signup(data).unwrap()
Не все поля data должны передаваться в сервис

2023-08-14 16:31 UTC, toropovofficial commented on packages/client/src/api/auth.ts
> +    signin: builder.mutation({
А не будет ли дублироваться запрос если сразу происходит редирект а юзера мы запрашиваем в роутере

2023-08-14 16:31 UTC, toropovofficial commented on packages/client/src/pages/Game/Game.tsx
> +        username: user?.login,
также поправим после внесения правок о которых писал выше

2023-08-15 06:00 UTC, apdashi commented on packages/client/src/pages/Game/Game.tsx
> +        username: user?.login,
Если ты про это https://github.com/PapakhinAV/yandex-practicum-game/blob/dev/packages/client/src/core/Router/Routes.tsx#L22 то тут он только раз срабатывает при запуске приложения и всё

2023-08-17 20:02 UTC, toropovofficial commented
Поправил ко комментариям

2023-08-19 12:12 UTC, toropovofficial commented
@dmitriy-kochetkov @PapakhinAV

2023-08-19 14:26 UTC, PapakhinAV commented on packages/client/src/utils/validators/validators.ts
> +export const lastNameValidator: TValidatorParam = (
есть же nameValidator, он вроде универсальный, зачем lastNameValidator?

2023-08-19 14:26 UTC, PapakhinAV commented on packages/client/src/store/Chunk.ts
> +
сам файл, наверное, должен называться не Chank, а Thunk, т.к. содержит thunk-функцию

2023-08-19 14:26 UTC, PapakhinAV commented on packages/client/src/store/Chunk.ts
> +      thunkAPI.dispatch(setRegisterError())
тут можно передавать в setRegisterError ту ошибку, которую мы можем получить в signinResult

2023-08-19 14:26 UTC, PapakhinAV commented on packages/client/src/store/Chunk.ts
> +      thunkAPI.dispatch(setLoginError())
тут можно сохранять ошибку, которую можем получить в signinResult, а потом её либо выводить, либо логировать)

2023-08-19 14:26 UTC, PapakhinAV commented on packages/client/src/core/Router/Routes.tsx
> +          <ProtectedRoute user={!user} redirectPath={ERoutes.HOME}>
если  user={!user} не параметр  именно пользователя, а какой-то флаг проверки, то может его переименовать в какой нибудь checkParam? (немного с толку сбивает когда передаётся !user)

2023-08-19 14:26 UTC, PapakhinAV commented on packages/client/src/core/Router/types.ts
> +  user: IUserState | null | boolean
и тут тогда можно будет оставить только boolean, если не привязываться в user

2023-08-19 14:26 UTC, PapakhinAV commented on packages/client/src/pages/Register/Register.tsx
> +  }))
Вот это
`dispatch(signupAndFetchUser({
      email: data.email,
      first_name: data.first_name,
      login: data.login,
      password: data.password,
      phone: data.phone,
      repeat_password: data.repeat_password,
      second_name: data.second_name
  }))`
можно заменить на 

`  dispatch(signupAndFetchUser({ ...data}))`

2023-08-21 09:49 UTC, toropovofficial commented
@PapakhinAV Поправил

2023-08-21 10:25 UTC, PapakhinAV approved these changes

2023-08-21 15:04 UTC, IvanPeleshok commented on packages/client/src/store/Thunk.ts
> +      return await thunkAPI.dispatch(authApi.endpoints.getUser.initiate())
В будущем предлагаю разделять return и await, т.к return await обычно не пишут (+ так ухудшается чтение кода)

2023-08-21 15:05 UTC, IvanPeleshok commented on packages/client/src/store/Thunk.ts
> +      return await thunkAPI.dispatch(authApi.endpoints.getUser.initiate())
Аналогично

2023-08-21 15:05 UTC, IvanPeleshok approved these changes
Замечательная работа, апрув

2023-08-21 15:15 UTC, merged