YAN-44 Настроить Express для Server Side Rendering
PapakhinAV/yandex-practicum-game pull request #27
Opened 2023-08-29 15:41 UTC by PapakhinAV

### Какую задачу решаем
- настроен Express-сервер, способный выполнять серверный рендеринг  
- подключен Redux на стороне SSR с передачейв стейта
- настроен роутинг SSR

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-29 17:06 UTC, apdashi submitted a review, later dismissed

2023-09-01 12:05 UTC, dmitriy-kochetkov submitted a review, later dismissed

2023-09-02 07:00 UTC, IvanPeleshok commented on packages/client/index.js
Нужен ли пустой файл?

2023-09-02 07:02 UTC, IvanPeleshok commented on packages/server/index.ts
> +  // createClientAndConnect()
Если не используется, то можно убрать

2023-09-02 07:14 UTC, IvanPeleshok commented on packages/server/index.ts
> +      const render = (await vite!.ssrLoadModule(path.resolve(srcPath, 'ssr.tsx'))).render
Правильно понимаю, что данная сборка только для дев разработки?
Не вижу, чтобы обрабатывался distPath для прода
Не пытались захостить своё приложение для того, чтобы протестировать на проде?

2023-09-02 07:15 UTC, IvanPeleshok requested changes
Крутая работа, всё прекрасно

Есть небольшой вопрос

2023-09-03 13:47 UTC, PapakhinAV commented on packages/client/index.js
Да, в видео про SSR (от практикума) было сказано, что index должен быть, чтобы в SSR корректно работала часть с  path.dirname(require.resolve(...)

2023-09-03 13:49 UTC, PapakhinAV commented on packages/server/index.ts
> +      const render = (await vite!.ssrLoadModule(path.resolve(srcPath, 'ssr.tsx'))).render
Ага, был только в dev режиме, внёс пракви и добавил прод режим.

P.S. тащить Chakra UI на проект с SSR было плохой идеей, из-за неё (точнее emotion, который является зависимостью) падала продовая сборка.

2023-09-03 14:24 UTC, IvanPeleshok approved these changes
Всё супер!

Работа принята!

2023-09-04 06:27 UTC, dmitriy-kochetkov approved these changes

2023-09-04 06:28 UTC, merged