Notification API
PapakhinAV/yandex-practicum-game pull request #29
Opened 2023-09-04 12:44 UTC by apdashi

Notification API

2023-09-06 15:42 UTC, PapakhinAV approved these changes

2023-09-07 19:22 UTC, Olegas requested changes
Добрый день.
В коде есть ошибка (написал комментарий)
Нужно переделать

2023-09-07 19:22 UTC, Olegas commented on packages/client/src/pages/Game/Game.tsx
> +      }
Получается что тут ошибка. Если на 54 строке пошли за разрешениями, а потом показали уведомление, то onlick на него навешен не будет

2023-09-09 14:17 UTC, Olegas approved these changes
Работа принята

2023-09-09 17:37 UTC, dmitriy-kochetkov approved these changes

2023-09-10 05:37 UTC, merged