YAN-54 Эмодзи
PapakhinAV/yandex-practicum-game pull request #40
Opened 2023-09-18 09:35 UTC by mironovsergey

### Добавлены реакции на топики форума

![Снимок экрана 2023-09-18 122657](https://github.com/PapakhinAV/yandex-practicum-game/assets/42154344/fde8e294-2bbd-442a-b65a-94da3099f1d6)

2023-09-19 03:52 UTC, PapakhinAV submitted a review, later dismissed

2023-09-19 07:40 UTC, PapakhinAV submitted a review, later dismissed

2023-09-20 17:11 UTC, Olegas requested changes
Добрый день.
Прошу прощения за долгое ревью.
Есть пара советов и проблема в реализации API. Написал подробно в комментариях.
Нужно доработать.

2023-09-20 17:11 UTC, Olegas commented on packages/server/services/forum/reaction.ts
> +    const { unified, topicId, userId } = req.body
Есть ли уже у вас в проекте middleware, которая проверяет авторизацию на API-ручках? Если да, то идентификатор пользователя надо брать оттуда, а не из тела запроса. Иначе можно наставить реакций от других пользователей

2023-09-20 17:11 UTC, Olegas commented on packages/server/services/forum/reaction.ts
> +      })
Данная проверка не будет нормально работать в условиях конкурентных запросов. Если придут два одинаковых запроса, оба проверят что записи нет и пойдут вставлять. Один из них упадет с исключением нарушения целостности первичного ключа.

2023-09-20 17:11 UTC, Olegas commented on packages/client/src/pages/Forum/components/Reaction/Reaction.tsx
> +  userIds: number[]
Совет по неймингу. Вот эти пропссы - unified и userIds - по ним не понятно что там лежит. Вот если бы они, например, назывались emoji и reactionOwners - было бы понятнее.
onClick хоть и понятно что делает (пользователь кликнул) но судя по коду это снятие реакции. Если назвать, допустим, onDismiss - станет читаемее.

(это не обязательно исправлять, просто совет)

2023-09-20 17:11 UTC, Olegas commented on packages/client/src/pages/Forum/components/Reaction/Reaction.tsx
> +  const isUserInUserIds = user?.id && userIds.includes(user.id)
Совет по неймингу: та же история, не понятно по имени, что это значит для приложения. Например wasSetByCurrentUser или что-то подобное - было бы сильно понятнее.

(это не обязательно исправлять, просто совет)

2023-09-21 17:06 UTC, Olegas approved these changes
Работа принята. Спасибо

2023-09-22 03:57 UTC, PapakhinAV approved these changes

2023-09-22 03:58 UTC, merged