Страница пользователя
PapakhinAV/yandex-practicum-game pull request #8
Opened 2023-07-22 15:33 UTC by apdashi

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-29 14:12 UTC, dmitriy-kochetkov submitted a review, later dismissed
Отличная работа!

👍 Станица открывается на роуте
👍 Изменение данных через модалку
👍 Валидация полей

🔥

2023-07-30 07:50 UTC, Olegas requested changes
Добрый день. 
Есть замечания по организации кода (скипнут тест, оставлен отладочный вывод).
Написал пару советов, как можно улучшить (типы данных в форме)
Нужно доработать.

2023-07-30 07:50 UTC, Olegas commented on packages/client/src/App/App.test.tsx
> +  test.skip('Отображает главную страницу', () => {
Почему пришлось скипать тесты? PR не должен ухудшать свойства приложения, то что раньше работало - должно продолжать работать.
Если есть какие-то особые обстоятельства - нужно написать рядом комментарий и объяснить что случилось и когда исправится.

2023-07-30 07:50 UTC, Olegas commented on packages/client/src/components/Button/Button.tsx
> +      className={classNames(className)}
Зачем тут classNames? className ведь строка?

2023-07-30 07:50 UTC, Olegas commented on packages/client/src/pages/Profile/ModalChangePassword.tsx
> +  console.log(useChangePasswordMutation())
Осталось от отладки и забыл удалить? Не надо оставлять в коде проекта отладочный вывод.

2023-07-30 07:50 UTC, Olegas commented on packages/client/src/components/Form/types.ts
> +  onSubmit: () => Promise<void>;
Неужели обработчику отправки формы не нужны значения самой формы? Мне кажется тип здесь не правильный, у функции должны быть какие-то аргументы

2023-07-30 07:50 UTC, Olegas commented on packages/client/src/components/fields/Input/Input.tsx
> +  return <Input {...props} {...register} className={classNames(className)} />
Тут тоже не понятно для чего используется classNames, ведь className это уже просто строка

2023-07-30 07:50 UTC, Olegas commented on packages/client/src/store/appReducer.ts
> +  sound: boolean;
Почему в типах то есть ; в конце строки то нет? Надо выбрать какой-то один стиль написания (судя по коду вокруг это стиль без ; ) и придерживаться его, желательно автоматически через eslint/prettier

2023-07-30 07:50 UTC, Olegas commented on packages/client/src/pages/Profile/ModalEdit.tsx
> +  const methods = useForm<Record<string, string>>({
В приложении есть тип данных пользователя, который используется в стейте. Его тут нельзя использовать для описания данных формы?

2023-07-31 19:35 UTC, Olegas approved these changes
Отлично, спасибо!
Работа принята.

2023-07-31 19:56 UTC, dmitriy-kochetkov approved these changes

2023-08-01 06:58 UTC, merged